// Package repo holds hand-written mocks for the repository interfaces. In
// deskapi these are generated by mockgen from the service-package
// definitions; we hand-roll them here so candidates can read them and so the
// project has no codegen dependency.
//
// The pattern is the simplest possible: each method has a function-typed
// field, and tests assign whatever behaviour they need. If a test forgets
// to set a behaviour the call returns the zero value, which is usually
// what the test wanted anyway.
package repo

import (
	"context"

	"library-api/models"
)

// AuthorRepo is a hand-rolled mock implementing services.AuthorRepository.
type AuthorRepo struct {
	ListFn      func(ctx context.Context, args *models.AuthorArgs) ([]*models.Author, int64, error)
	ListByIDsFn func(ctx context.Context, ids []int64) ([]*models.Author, error)
	CreateFn    func(ctx context.Context, a *models.Author) error
	UpdateFn    func(ctx context.Context, a *models.Author) error
	DeleteFn    func(ctx context.Context, id int64) error

	// Calls counts each method's invocations so tests can assert on
	// interaction patterns without storing the call args by hand.
	Calls struct {
		List, ListByIDs, Create, Update, Delete int
	}
}

func (m *AuthorRepo) List(ctx context.Context, args *models.AuthorArgs) ([]*models.Author, int64, error) {
	m.Calls.List++
	if m.ListFn == nil {
		return nil, 0, nil
	}
	return m.ListFn(ctx, args)
}

func (m *AuthorRepo) ListByIDs(ctx context.Context, ids []int64) ([]*models.Author, error) {
	m.Calls.ListByIDs++
	if m.ListByIDsFn == nil {
		return nil, nil
	}
	return m.ListByIDsFn(ctx, ids)
}

func (m *AuthorRepo) Create(ctx context.Context, a *models.Author) error {
	m.Calls.Create++
	if m.CreateFn == nil {
		return nil
	}
	return m.CreateFn(ctx, a)
}

func (m *AuthorRepo) Update(ctx context.Context, a *models.Author) error {
	m.Calls.Update++
	if m.UpdateFn == nil {
		return nil
	}
	return m.UpdateFn(ctx, a)
}

func (m *AuthorRepo) Delete(ctx context.Context, id int64) error {
	m.Calls.Delete++
	if m.DeleteFn == nil {
		return nil
	}
	return m.DeleteFn(ctx, id)
}
