package iservices

import (
	"context"

	"library-api/models"
)

// AuthorService is the public surface every caller depends on (controllers,
// other services, tests). It is hand-written here rather than generated to
// keep the project self-contained — in deskapi the equivalent file is
// generated by ifacemaker.
type AuthorService interface {
	// Get returns one author by id. Returns *models.HTTPError(404) when the
	// author does not exist.
	Get(ctx context.Context, args *models.AuthorArgs) (*models.AuthorBody, error)

	// List returns a page of authors plus pagination metadata.
	List(ctx context.Context, args *models.AuthorArgs) (*models.AuthorsBody, error)

	// Create persists a new author. The service stamps the audit trail
	// before calling the repository.
	Create(ctx context.Context, body *models.AuthorBody) error

	// Update applies the changes in body to the existing author with the
	// same id.
	Update(ctx context.Context, body *models.AuthorBody) error

	// Delete soft-deletes the author by default (state="deleted"); pass
	// args.HardDelete=true to remove the row.
	Delete(ctx context.Context, args *models.AuthorArgs) error
}
