// Package iservices holds every service interface plus the ServiceLocator
// interface that ties them together.
//
// In deskapi this package is generated by `ifacemaker`; here we hand-write
// it. The shape is deliberately the same so candidates recognise:
//
//   - Each service has its own interface, named {Resource}Service.
//   - There is one umbrella ServiceLocator that exposes every service via a
//     method that takes a context. Controllers and other services depend
//     only on this interface, never on concrete service types.
//   - The locator interface is what gets mocked in unit tests, so a service
//     can be tested in isolation without instantiating any of its peers.
package iservices

import "context"

// ServiceLocator is the dependency-injection seam for every service. A
// controller takes a ServiceLocator, asks it for the service it needs, and
// invokes a method:
//
//	body, err := h.svc.Book(ctx).List(ctx, &args)
//
// The accessor takes a context so that a real implementation can return a
// service scoped to the request (e.g. with a per-request transaction or
// permission check). Our concrete locator just returns the same instance
// every time, but candidates should keep the signature.
type ServiceLocator interface {
	Author(ctx context.Context) AuthorService
	Book(ctx context.Context) BookService
	Publisher(ctx context.Context) PublisherService
}
